name: km_test_suitmedia_resmaadi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.2.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  slang: ^3.31.1
  google_fonts: ^6.2.1
  remixicon: ^1.2.0
  toastification: ^2.0.0
  flutter_screenutil: ^5.9.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  flutter_pdfview: ^1.3.2
  equatable: ^2.0.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  flutter_easyloading: ^3.0.5
  http: ^1.2.1
  file_picker: ^8.0.5
  webview_flutter: ^4.8.0
  dartz: ^0.10.1
  envied: ^0.5.4+1
  freezed: ^2.5.2
  flutter_tabler_icons: ^1.33.0
  sliding_clipped_nav_bar: ^3.1.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^10.0.1
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  intl: ^0.19.0
  rflutter_alert: ^2.0.7
  http_parser: ^4.0.2
  flutter_recaptcha_v2_compat: ^1.0.5
  fl_chart: ^0.68.0
  bottom_sheet: ^4.0.4
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0
  change_app_package_name: ^1.3.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
